steps:
  test:
    image: ghcr.io/astral-sh/uv:0.12.6-python3.14-alpine3.23
    commands:
      - uv sync --frozen --extra testing
      - uv run coverage run -m pytest
      - uv run coverage report -m
      - uv run coverage xml -o coverage.xml
    when:
      branch: main
      event: [push, pull_request]

  sonarqube:
    image: sonarsource/sonar-scanner-cli:12.1.0.3233_8.0.1
    environment:
      SONAR_HOST_URL:
        from_secret: sonar_host_url
      SONAR_TOKEN:
        from_secret: sonar_token
    commands:
      - sonar-scanner
    when:
      branch: main
      event: [push, pull_request]
