[project]
name = "Discord-OTP-Forcer"
version = "0.5.5"
description = "Selenium based discord OTP forcer"
requires-python = ">=3.11"
dependencies = [
    "seleniumbase==4.52.4",
    "PyYAML==6.0.3",
    "stackprinter==0.2.13",
    "loguru==0.7.3",
    "regex-string-generator==0.1.0",
]

[project.optional-dependencies]
testing = [
    "pytest==9.1.1",
    "pytest-mock==3.15.1",
    "coverage==7.16.0",
    "hypothesis==6.165.2"
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
source = ["src"]

[tool.coverage.report]
show_missing = true

[tool.uv]
package = false

[tool.basedpyright]
venvPath = "."
venv = ".venv"
typeCheckingMode = "standard"
reportUnknownVariableType = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
reportUnknownParameterType = false

[tool.ruff.lint]
ignore = ["E701", "F841"]

[tool.ruff.format]
quote-style = "preserve"
line-ending = "lf"

[tool.ruff]
line-length = 170
