# THIS FILE CONTAINS SENSITIVE LOGIN INFORMATION FOR YOUR DISCORD ACCOUNT!
#
# TAKE UTMOST CARE WHEN HANDLING, WORKING ON, OR UPLOADING THIS FILE.
#
# IF YOU CHECK THIS FILE INTO A PUBLIC-FACING VERSION CONTROL REPO, UPLOAD IT ONLINE,
# OR SHARE IT TO ANYONE YOU DON'T FULLY TRUST, YOUR INFORMATION AND ACCOUNT COULD POTENTIALLY BE STOLEN!!!
#
# IF YOUR DISCORD, EMAIL, OR OTHER ACCOUNT OR PERSONAL INFORMATION GETS HACKED, CRACKED, OR OTHERWISE STOLEN BECAUSE
# YOU SHARED YOUR FILLED IN COPY OF THIS FILE TO ANYONE,
# THE AUTHORS AND CONTRIBUTORS OF THIS PROGRAM ARE NOT RESPONSIBLE FOR WHATEVER DAMAGES MAY ENSUE

# Basic login info

email: ""
password: ""

# Password Reset Info
#
# To get your token it will be in the url of the password reset page.
# Follow the instructions in the README.md on how to obtain this token

newPassword: ""
resetToken: ""

# This option isn't implemented yet. Filling it out doesn't do anything (yet)
authToken: ""
